sudo: true
dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - sudo add-apt-repository ppa:artyom.h31/3proxy -y
  - sudo apt-get update
  - sudo apt-get install 3proxy -y
script:
  - cargo build --verbose --all
  - cargo test --lib --verbose
  - tests/integration_tests.sh
