[package]
name = "tokio-socks"
description = "Asynchronous SOCKS proxy support for Rust."
documentation = "https://docs.rs/tokio-socks"
homepage = "https://github.com/sticnarf/tokio-socks"
repository = "https://github.com/sticnarf/tokio-socks"
readme = "README.md"
categories = ["asynchronous", "network-programming"]
keywords = ["tokio", "async", "proxy", "socks", "socks5"]
license = "MIT"
version = "0.1.3"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "sticnarf/tokio-socks" }

[dependencies]
futures= {version= "0.3.0-alpha.19", package="futures-preview"}
tokio-net = {version="0.2.0-alpha.6", features=["tcp"]}
tokio-io = {version="0.2.0-alpha.6", features=["util"]}
bytes = "0.4"
failure = "0.1"
derefable = "0.1"
either = "1"

[dev-dependencies]
tokio = "0.2.0-alpha.6"
once_cell = "1.2.0"
hyper = "0.12.35"
